# Generated by Django 4.0.4 on 2022-09-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('travellers', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuestPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=1500)),
                ('keuword', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='INSTA')),
                ('date', models.DateField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
