# Generated by Django 4.0.4 on 2022-09-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0007_blogplanmytour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogplanmytour',
            name='name',
        ),
    ]
