# Generated by Django 3.2.8 on 2022-10-25 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0009_rename_keuword_guestpost_keyword_guestpost_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPlanMyTour',
        ),
        migrations.DeleteModel(
            name='ContactDestination',
        ),
        migrations.DeleteModel(
            name='ContactLanding',
        ),
        migrations.DeleteModel(
            name='GuestPost',
        ),
        migrations.DeleteModel(
            name='PlanMyTour',
        ),
        migrations.DeleteModel(
            name='PlanMyTourDestination',
        ),
    ]
