# Generated by Django 3.2.8 on 2022-11-10 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0010_auto_20221025_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='STLFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='STLFileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='STL FILE')),
                ('date', models.DateField(auto_now_add=True)),
                ('stl_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.stlfile')),
            ],
        ),
    ]
