# Generated by Django 3.2.8 on 2022-11-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0011_stlfile_stlfiledata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stlfile',
            name='subject',
        ),
    ]
