# Generated by Django 3.2.8 on 2022-11-16 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0012_remove_stlfile_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stlfiledata',
            name='stl_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enquiry.stlfile'),
        ),
    ]
