# Generated by Django 3.2.8 on 2022-12-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0013_alter_stlfiledata_stl_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='stlfile',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='STL FILE'),
        ),
    ]
