# Generated by Django 4.1.4 on 2022-12-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0015_alter_stlfile_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stlfile',
            name='files',
        ),
    ]
