# Generated by Django 4.1.4 on 2022-12-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0016_remove_stlfile_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stlfiledata',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='STL FILE'),
        ),
    ]
