# Generated by Django 4.1.4 on 2022-12-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0017_alter_stlfiledata_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stlfiledata',
            old_name='files',
            new_name='file1',
        ),
        migrations.AddField(
            model_name='stlfiledata',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='STL FILE'),
        ),
        migrations.AddField(
            model_name='stlfiledata',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='STL FILE'),
        ),
        migrations.AddField(
            model_name='stlfiledata',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='STL FILE'),
        ),
        migrations.AddField(
            model_name='stlfiledata',
            name='file5',
            field=models.FileField(blank=True, null=True, upload_to='STL FILE'),
        ),
        migrations.AddField(
            model_name='stlfiledata',
            name='file6',
            field=models.FileField(blank=True, null=True, upload_to='STL FILE'),
        ),
        migrations.AddField(
            model_name='stlfiledata',
            name='file7',
            field=models.FileField(blank=True, null=True, upload_to='STL FILE'),
        ),
    ]
