# Generated by Django 4.1.4 on 2022-12-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0018_rename_files_stlfiledata_file1_stlfiledata_file2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stlfiledata',
            name='name',
            field=models.CharField(default='STL File Data', max_length=150),
        ),
    ]
