# Generated by Django 4.1.4 on 2022-12-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0019_stlfiledata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stlfiledata',
            name='file1',
            field=models.FileField(upload_to='STL FILE'),
        ),
    ]
