# Generated by Django 4.1.4 on 2022-12-20 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0020_alter_stlfiledata_file1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stlfiledata',
            old_name='file1',
            new_name='files',
        ),
        migrations.RemoveField(
            model_name='stlfiledata',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='stlfiledata',
            name='file3',
        ),
        migrations.RemoveField(
            model_name='stlfiledata',
            name='file4',
        ),
        migrations.RemoveField(
            model_name='stlfiledata',
            name='file5',
        ),
        migrations.RemoveField(
            model_name='stlfiledata',
            name='file6',
        ),
        migrations.RemoveField(
            model_name='stlfiledata',
            name='file7',
        ),
        migrations.RemoveField(
            model_name='stlfiledata',
            name='name',
        ),
    ]
