# Generated by Django 3.2 on 2023-04-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0021_rename_file1_stlfiledata_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stlfiledata',
            name='files',
            field=models.FileField(upload_to='STL_FILE'),
        ),
    ]
