# Generated by Django 3.2.8 on 2022-10-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='breadcrumb',
            field=models.CharField(max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='canonical',
            field=models.CharField(default='https://myoneblog.com/', max_length=900),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='SEO'),
        ),
        migrations.AddField(
            model_name='category',
            name='keyword',
            field=models.CharField(max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='og_card',
            field=models.CharField(max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='og_site',
            field=models.CharField(max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='og_type',
            field=models.CharField(max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=1256, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=156, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='primary',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
