# Generated by Django 3.2.8 on 2022-10-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20221013_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main3',
            field=models.BooleanField(default=False),
        ),
    ]
