# Generated by Django 3.2.8 on 2022-10-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_main3'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='most_visited',
            field=models.BooleanField(default=False),
        ),
    ]
