# Generated by Django 3.2.8 on 2022-10-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_events_eventsgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.CharField(blank=True, max_length=1256, null=True),
        ),
    ]
