# Generated by Django 3.2.8 on 2022-10-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20221014_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subproduct',
            name='tag',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(null=True, to='blog.Category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(null=True, to='blog.Tags'),
        ),
    ]
