# Generated by Django 3.2.8 on 2022-10-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20221014_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faqpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=156)),
                ('answer', models.CharField(max_length=156)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.product')),
                ('subproduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.subproduct')),
            ],
        ),
    ]
