# Generated by Django 3.2.8 on 2022-10-14 17:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_faqpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqpage',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='question',
            field=models.CharField(max_length=1156),
        ),
    ]
