# Generated by Django 3.2.8 on 2022-12-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTestimonals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SEO')),
                ('name', models.CharField(max_length=156)),
                ('position', models.CharField(max_length=156)),
                ('review', models.TextField()),
            ],
        ),
    ]
