# Generated by Django 3.2.8 on 2022-12-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_videotestimonals_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotestimonals',
            name='image',
        ),
        migrations.RemoveField(
            model_name='videotestimonals',
            name='review',
        ),
        migrations.AlterField(
            model_name='videotestimonals',
            name='position',
            field=models.CharField(default='Dentist', max_length=156),
        ),
    ]
