# Generated by Django 3.2.8 on 2023-01-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20221206_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotestimonals',
            name='video',
        ),
        migrations.AddField(
            model_name='videotestimonals',
            name='link',
            field=models.CharField(blank=True, max_length=1256, null=True),
        ),
    ]
